# Generated by Django 4.0 on 2022-05-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, upload_to='media/products')),
                ('status', models.CharField(choices=[('in stock', 'в наличии'), ('out of stock', 'нет в наличии')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='category.category')),
            ],
        ),
    ]
