# Generated by Django 4.0 on 2022-05-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'test'), ('out of stock', 'test')], max_length=20),
        ),
    ]
