# Generated by Django 4.0 on 2022-05-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_slug_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
