# Generated by Django 4.0 on 2022-05-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'в наличии'), ('out of stock', 'нет в наличии')], max_length=20),
        ),
    ]
